### ISSUE TITLE
About processing when REQUEST_CODE is different

### ISSUE THREAD

**Issue by kan** [granoeste/flutter_line_login#2]
https://github.com/granoeste/flutter_line_login/blob/master/android/src/main/kotlin/net/granoeste/flutterlinelogin/FlutterLineLoginPlugin.kt#L196-L202

Should you simply return false in the above part? In the current code seems to interfere with plugins that use other `onActivityResult`.
I have confirmed that by modifying it, you can use it with the [google_sign_in plugin](https://pub.dartlang.org/packages/google_sign_in) at the same time.

**Comment by skybur** [comment]
I have also experienced this. I used `google_sign_in` in my app and after signing in with google, this plugin throws an error.

**Comment by granoeste** [comment]
@kan Thanks for the report.
This problem was fixed in 0.1.4 and published.
