### ISSUE TITLE
How can I check when Web login browser X button close?

### ISSUE THREAD

**Issue by hwangjundong** [granoeste/flutter_line_login#3]
How can I check when Web login browser X button close?

Error event is not fired.

**Comment by granoeste** [comment]
Supported by [release 0.2.0](https://github.com/granoeste/flutter_line_login/releases/tag/0.2.0)

Notify to @hwangjundong 
Maybe you can check in  `onError` Function. 
Unfortunately, Login failed details differs between Android and iOS. In Android, you can get reason from responseCode of function's argument object. In iOS, you can only guess from description of function's argument object.
