### ISSUE TITLE
please  Podspec -> s.static_framework = true

### ISSUE THREAD

**Issue by show1111** [granoeste/flutter_line_login#4]
[!] The 'Pods-Runner' target has transitive dependencies that include static binaries: 

Podspec -> s.static_framework = true

お願いいたします。ありがとうございます。

**Comment by show1111** [comment]
ios/.symlinks/plugins/flutter_line_login/ios/flutter_line_login.podspec     <----- edit   

아오 내가 고쳐씀

**Comment by granoeste** [comment]
Why do you want it? What is the problem occurring?

thx

**Comment by hoangnguyendn** [comment]
This is will avoid error when use use_frameworks! on iOS

**Comment by granoeste** [comment]
Supported by [release 0.2.0](https://github.com/granoeste/flutter_line_login/releases/tag/0.2.0)

Notify to @hoangnguyendn
